# Generated by Django 5.0.4 on 2024-04-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0003_alter_play_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('attempt2', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('attempt3', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('attempt4', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('attempt5', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('attempt6', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordleND.play')),
            ],
        ),
    ]
