# Generated by Django 5.0.4 on 2024-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0004_play_in_progress_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
