# Generated by Django 5.0.4 on 2024-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0005_play_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='lang',
            new_name='language',
        ),
        migrations.AddField(
            model_name='play',
            name='word',
            field=models.CharField(default='MILES', max_length=5),
        ),
    ]
