# Generated by Django 5.0.4 on 2024-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0006_rename_lang_play_language_play_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='game_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date played'),
        ),
    ]
