# Generated by Django 5.0.4 on 2024-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0007_alter_play_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_plays',
            field=models.IntegerField(default=0),
        ),
    ]
