# Generated by Django 5.0.3 on 2024-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleND', '0008_profile_extra_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='attempt1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='attempt2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='attempt3',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='attempt4',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='attempt5',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='attempt6',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
